### ISSUE TITLE
Crashed game opening after launch

### ISSUE THREAD

**Issue by mrfrase3** [heinwessels/factorio-spidertron-dock#1] opened 2023-07-02 08:56 UTC
After launching my spaceship, and clicking on the docked spider, I got the following error:

```
The mod Spidertron Dock (1.0.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event spidertron-dock::on_gui_opened (ID 88)
__spidertron-dock__/control.lua:1151: attempt to index local 'spider_data' (a nil value)
stack traceback:
	__spidertron-dock__/control.lua:1151: in function 'update_spider_gui_for_player'
	__spidertron-dock__/control.lua:1235: in function <__spidertron-dock__/control.lua:1228>
```

Undocking the spider, then also causes this error:

```
Error while running event spidertron-dock::on_gui_click (ID 1)
__spidertron-dock__/lib/spidertron_lib.lua:215: attempt to index local 'serialised_data' (a nil value)
stack traceback:
	__spidertron-dock__/lib/spidertron_lib.lua:215: in function 'deserialise_spidertron'
	__spidertron-dock__/control.lua:334: in function 'dock_from_serialised_to_spider'
	__spidertron-dock__/control.lua:471: in function 'undock_spider'
	__spidertron-dock__/control.lua:558: in function 'attempt_undock'
	__spidertron-dock__/control.lua:1265: in function <__spidertron-dock__/control.lua:1250>
```

Attempting to destroy the dock:
```
Error while running event spidertron-dock::on_player_mined_entity (ID 67)
__spidertron-dock__/lib/spidertron_lib.lua:215: attempt to index local 'serialised_data' (a nil value)
stack traceback:
	__spidertron-dock__/lib/spidertron_lib.lua:215: in function 'deserialise_spidertron'
	__spidertron-dock__/control.lua:334: in function 'dock_from_serialised_to_spider'
	__spidertron-dock__/control.lua:471: in function 'undock_spider'
	__spidertron-dock__/control.lua:558: in function 'attempt_undock'
	__spidertron-dock__/control.lua:790: in function <__spidertron-dock__/control.lua:782>
```

These errors occur:
- not when I'm in orbit (about to leave)
- launched but not yet engaged
- launched and engaged
- arrived and not yet anchored
- after anchoring at the destination
- with a fresh spider (nothing modded in the grid, empty inv)

My cursory glance at the code indicates the spider's data might be getting wiped from the dock after launch, I'm no modding expert though. Let me know if you want me to test other permutations.

I am using Space Exploration 0.5.107, Factorio 1.1.80.

Thanks for the mod, I've enjoyed zipping around the space factory.

Also as a side note, the space spidertrons don't seem to [wear the sunglasses](https://mods.factorio.com/mod/spidertron-deal-with-it).

**Comment by heinwessels** [comment] 2023-08-02 10:20
Hello @mrfrase3! Sorry that I'm responding now. For some reason I wasn't receiving e-mails about issues opened on my repos.

Unfortunately the problem is that you're still playing SE 0.5. When I made Spidertron Dock a separate mod I removed compatability with 0.5, but forgot to make it a requirement. Not sure yet if I will add it back.

Your options now:
- If you removed Spidertron Dock and Space Spidertron mod you could simply install Space Spidertron V1.2.3.
- If you still have the Space Spidertron and/or Spidertron Dock installed with many existing entities, then it's a little harder. Because you can't revert to the old Space Spidertron version then.

I will try to add compatability for 0.5 again, but I can't make any promises on when that might happen.

---

As for the sunglasses, something will have to be done about that :P

**Comment by heinwessels** [comment] 2024-10-01 08:50
Closing, since 0.5 isn't supported

**Closed as completed by heinwessels** 2024-10-01 08:50 UTC

**Comment by mrfrase3** [comment] 2024-10-01 10:11
nw, I think I ended up just put the Spidertron into my inventory before launching or something. thanks anyway.
